version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flask-app:
    image: python:3.9
    container_name: flask-app
    volumes:
      - ./app:/app
    working_dir: /app
    command: /bin/bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5001:5000"
    depends_on:
      - mongo

volumes:
  mongo-data:
